In [15]:
import pandas as pd

In [17]:
df = pd.read_csv(r"C:\Users\putna\Downloads\recomandation sysytem\tmdbdf.csv")

In [18]:
df=df.head(5000)

In [19]:
x = df.drop(columns = ['Unnamed: 0','index'],axis=1)

In [20]:
df.shape

(5000, 8)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.isna().sum()

Unnamed: 0      0
index           0
id              0
title           0
overview        0
keywords       77
genres          0
poster_path     0
dtype: int64

In [23]:
df.describe()

        Unnamed: 0        index            id
count  5000.000000  5000.000000  5.000000e+03
mean   2499.500000  2499.500000  1.656111e+05
std    1443.520003  1443.520003  2.294867e+05
min       0.000000     0.000000  5.000000e+00
25%    1249.750000  1249.750000  8.426250e+03
50%    2499.500000  2499.500000  2.433550e+04
75%    3749.250000  3749.250000  3.019452e+05
max    4999.000000  4999.000000  1.140066e+06

In [24]:
df.describe(include='object')

,title,overview,keywords,genres,poster_path
count,5000,5000,4923,5000,5000
unique,4888,5000,4900,1377,5000
top,Pinocchio,"Cobb, a skilled thief who commits corporate es...",duringcreditsstinger,Comedy,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
freq,4,1,5,246,1

In [25]:
df['tag']=df['overview'].fillna(' ')+df['keywords'].fillna(' ')+df['genres'].fillna(' ')
df['tag']

0       Cobb, a skilled thief who commits corporate es...
1       The adventures of a group of explorers who mak...
2       Batman raises the stakes in his war on crime. ...
3       In the 22nd century, a paraplegic Marine is di...
4       When an unexpected enemy emerges and threatens...
                              ...
4995    What do you dream of when you're 16-years-old ...
4996    When his young daughter's beloved companion — ...
4997    Three years after her relationship with Giovan...
4998    Two turkeys from opposite sides of the tracks ...
4999    The tale of two brothers with serious financia...
Name: tag, Length: 5000, dtype: object

In [26]:
df['tag'].isna().sum()

np.int64(0)

### Lower case

In [27]:
df['tag']=df['tag'].apply(lambda x:x.lower())
df['tag']

0       cobb, a skilled thief who commits corporate es...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime. ...
3       in the 22nd century, a paraplegic marine is di...
4       when an unexpected enemy emerges and threatens...
                              ...
4995    what do you dream of when you're 16-years-old ...
4996    when his young daughter's beloved companion — ...
4997    three years after her relationship with giovan...
4998    two turkeys from opposite sides of the tracks ...
4999    the tale of two brothers with serious financia...
Name: tag, Length: 5000, dtype: object

## Remove tags and panctuations

In [28]:
#df['tag']=df['tag'].str.replace(r'[^\w\s]','',regex=True)

#df['tag']

## stemming

In [29]:
from nltk.stem import PorterStemmer

In [30]:
ps=PorterStemmer()

In [31]:
ps.stem('running')

'run'

In [32]:
def steming(word):
    y = []
    for i in word.split():
        y.append(ps.stem(i))
    return' '.join(y)

In [33]:
df['tag']

0       cobb, a skilled thief who commits corporate es...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime. ...
3       in the 22nd century, a paraplegic marine is di...
4       when an unexpected enemy emerges and threatens...
                              ...
4995    what do you dream of when you're 16-years-old ...
4996    when his young daughter's beloved companion — ...
4997    three years after her relationship with giovan...
4998    two turkeys from opposite sides of the tracks ...
4999    the tale of two brothers with serious financia...
Name: tag, Length: 5000, dtype: object

In [34]:
df['tag']=df['tag'].apply(steming)
df['tag']

0       cobb, a skill thief who commit corpor espionag...
1       the adventur of a group of explor who make use...
2       batman rais the stake in hi war on crime. with...
3       in the 22nd century, a parapleg marin is dispa...
4       when an unexpect enemi emerg and threaten glob...
                              ...
4995    what do you dream of when you'r 16-years-old a...
4996    when hi young daughter' belov companion — an a...
4997    three year after her relationship with giovann...
4998    two turkey from opposit side of the track must...
4999    the tale of two brother with seriou financi wo...
Name: tag, Length: 5000, dtype: object

## Converting into vecotors

In [35]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [36]:
tf=TfidfVectorizer(max_features=21000,stop_words='english')

In [37]:
vector = tf.fit_transform(df['tag'])

In [38]:
tf.get_feature_names_out().tolist()

['00',
 '000',
 '007',
 '10',
 '100',
 '101',
 '10thcentury',
 '11',
 '117',
 '11drama',
 '11th',
 '11thcentury',
 '12',
 '120',
 '1200',
 '12th',
 '12thcentury',
 '13',
 '14',
 '1453',
 '1492',
 '14th',
 '14thcentury',
 '15',
 '150',
 '15th',
 '15thcentury',
 '16',
 '16th',
 '16thcentury',
 '17',
 '17th',
 '17thcentury',
 '17thcenturydrama',
 '18',
 '1800s',
 '1862',
 '1863',
 '1870s',
 '1879',
 '1890',
 '1890s',
 '1892',
 '18th',
 '18thcentury',
 '19',
 '1900',
 '1900s',
 '1910',
 '1910s',
 '1916',
 '1917',
 '1920',
 '1920s',
 '1920sdrama',
 '1925',
 '1927',
 '1930',
 '1930s',
 '1930sadventure',
 '1930scomedy',
 '1930scrime',
 '1930sdrama',
 '1931',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1940s',
 '1940saction',
 '1940scomedy',
 '1940sdrama',
 '1940swar',
 '1941',
 '1942',
 '1944',
 '1945',
 '1947',
 '1949',
 '1950',
 '1950s',
 '1950saction',
 '1950scrime',
 '1950sdrama',
 '1952',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1960',
 '1960s',
 '1960saction',
 '1960scomedy',
 '1960scrime',
 '1960sdrama',
 '1962',
 '1963',
 '1964',
 '1965',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1980saction',
 '1980scomedy',
 '1980scrime',
 '1980sdrama',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1990',
 '1990s',
 '1990scomedy',
 '1990scrime',
 '1990sdrama',
 '1990shorror',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19comedi',
 '19th',
 '19thcentury',
 '19thcenturyadventure',
 '19thcenturyanimation',
 '19thcenturydrama',
 '19thcenturywestern',
 '1stcentury',
 '1stcenturyfamily',
 '20',
 '200',
 '2000s',
 '2000ssciencefiction',
 '2001',
 '2002',
 '2003',
 '2004',
 '2008',
 '2009',
 '2010',
 '2010s',
 '2011',
 '2013',
 '2015',
 '2016',
 '2019',
 '2028',
 '2029',
 '2030s',
 '2030saction',
 '2035',
 '2040s',
 '2040saction',
 '2060s',
 '2070saction',
 '20s',
 '20th',
 '21',
 '21st',
 '22',
 '22nd',
 '22ndcentury',
 '23',
 '23rd',
 '23rdcentury',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '2ndcentury',
 '30',
 '300',
 '30s',
 '30th',
 '31',
 '34',
 '35',
 '39',
 '3danimation',
 '3po',
 '40',
 '400',
 '43',
 '45',
 '47',
 '476',
 '49',
 '50',
 '500',
 '51',
 '5thcenturybc',
 '60',
 '600',
 '60s',
 '70',
 '70s',
 '72',
 '75',
 '80',
 '800',
 '80sthrowback',
 '86',
 '90',
 '90s',
 '911',
 '95',
 'aaron',
 'abandon',
 'abandoned',
 'abandonedbaby',
 'abandonedhouse',
 'abandonedmine',
 'abandonment',
 'abba',
 'abbey',
 'abbi',
 'abby',
 'abduct',
 'abducted',
 'abduction',
 'abe',
 'abid',
 'abigail',
 'abil',
 'abilities',
 'abl',
 'aboard',
 'abod',
 'abolitionist',
 'abortion',
 'abov',
 'abra',
 'abraham',
 'abrahamlincoln',
 'abroad',
 'abrupt',
 'absenc',
 'absent',
 'absolut',
 'absorb',
 'absurd',
 'absurdcomedy',
 'absurdism',
 'abus',
 'abuse',
 'abusedwoman',
 'abuseofpower',
 'abusive',
 'abusivefamily',
 'abusivehusband',
 'abusivemarriage',
 'abusivemother',
 'aca',
 'academ',
 'academi',
 'academia',
 'academy',
 'acapella',
 'accents',
 'accept',
 'acceptance',
 'access',
 'accid',
 'accident',
 'accidentaldeath',
 'accidentdrama',
 'acclaim',
 'accommod',
 'accompani',
 'accomplic',
 'accomplices',
 'accomplish',
 'accord',
 'account',
 'accountant',
 'accounts',
 'accus',
 'accusedofmurder',
 'ace',
 'ach',
 'achiev',
 'acid',
 'acknowledg',
 'acm',
 'acquaint',
 'acquir',
 'acquit',
 'acr',
 'act',
 'action',
 'actionhero',
 'actionheroaction',
 'actionheroadventure',
 'actionherothriller',
 'actions',
 'activ',
 'activist',
 'activistdrama',
 'activities',
 'activity',
 'actor',
 'actorplayingthemselfcomedy',
 'actors',
 'actress',
 'actual',
 'acupuncture',
 'ad',
 'ada',
 'adalin',
 'adam',
 'adams',
 'adapt',
 'adaptation',
 'add',
 'addam',
 'addict',
 'addicted',
 'addiction',
 'addit',
 'addl',
 'address',
 'adel',
 'adelaid',
 'adjust',
 'adler',
 'administr',
 'admir',
 'admired',
 'admiring',
 'admit',
 'admonit',
 'adolesc',
 'adolescence',
 'adolf',
 'adolfhitler',
 'adolfhitlerdrama',
 'adoni',
 'adopt',
 'adoptedchild',
 'adoptedson',
 'adoption',
 'adoptivefather',
 'ador',
 'adoring',
 'adrenalin',
 'adrenaline',
 'adrenalinejunkie',
 'adrian',
 'adrift',
 'adult',
 'adultanimation',
 'adultanimationanimation',
 'adultasachild',
 'adultery',
 'adulthood',
 'adults',
 'advanc',
 'advancement',
 'advantag',
 'advantage',
 'adventur',
 'adventure',
 'adventurer',
 'adventures',
 'adversari',
 'adversaries',
 'adversary',
 'advertis',
 'advertising',
 'advertisingexecutive',
 'advertisingexpert',
 'advic',
 'advice',
 'advicecolumnist',
 'advis',
 'advisor',
 'advoc',
 'aerial',
 'aerialcombat',
 'affabl',
 'affair',
 'affairs',
 'affect',
 'affection',
 'afflict',
 'afford',
 'afghan',
 'afghanistan',
 'afghanistanwar',
 'afoul',
 'afraid',
 'africa',
 'african',
 'africanamericanchild',
 'africanamericandrama',
 'africanamericanhistory',
 'africanamericanhistorydrama',
 'aftercreditsstinger',
 'aftercreditsstingeraction',
 'aftercreditsstingeradventure',
 'aftercreditsstingercomedi',
 'aftercreditsstingercomedy',
 'aftercreditsstingercrime',
 'aftercreditsstingerfamily',
 'afterlif',
 'afterlife',
 'aftermath',
 'afternoon',
 'ag',
 'againsttheodds',
 'agamemnon',
 'agatha',
 'age',
 'aged',
 'agedifference',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agentadventure',
 'agents',
 'aggie',
 'aggress',
 'aggression',
 'aggressive',
 'aggressors',
 'aging',
 'agingactor',
 'ago',
 'agoraphobia',
 'agre',
 'agrees',
 'agu',
 'ahead',
 'ahsoka',
 'aid',
 'aida',
 'aide',
 'aids',
 'ail',
 'aim',
 'aime',
 'aimless',
 'air',
 'airborn',
 'aircraft',
 'aircraftcarrier',
 'airforce',
 'airforceone',
 'airlin',
 'airpirate',
 'airplan',
 'airplane',
 'airplaneaccident',
 'airplanecrash',
 'airplanehijacking',
 'airplanepilot',
 'airplanewreck',
 'airport',
 'airportlounge',
 'airship',
 'airtrafficcontrol',
 'aisle',
 'aka',
 'akelarre',
 'aki',
 'akira',
 'al',
 'alabama',
 'aladdin',
 'alan',
 'alarm',
 'alarmclock',
 'alaska',
 'alaskan',
 'albanian',
 'albeit',
 'albert',
 'alberto',
 'albino',
 'album',
 'alcatraz',
 'alcatrazprison',
 'alchemy',
 'alcohol',
 'alcoholabuse',
 'alcoholic',
 'alcoholism',
 'aldo',
 'aldou',
 'alec',
 'alejandro',
 'alert',
 'alex',
 'alexand',
 'alexander',
 'alexanderthegreat',
 'alexia',
 'alfi',
 'alfr',
 'algerian',
 'algorithm',
 'algren',
 'ali',
 'alias',
 'alibi',
 'alic',
 'alice',
 'alicia',
 'alien',
 'alienabduction',
 'alienation',
 'alienattack',
 'aliencontact',
 'aliencreature',
 'alienencounter',
 'alienfriendship',
 'alieninfection',
 'alieninvasion',
 'alieninvasionsciencefiction',
 'alienlanguage',
 'alienlife',
 'alienmonster',
 'alienparasites',
 'alienplanet',
 'alienrace',
 'aliens',
 'alienspacecraft',
 'alientechnology',
 'alik',
 'alike',
 'alisdair',
 'aliv',
 'alive',
 'allan',
 'alleg',
 'allegations',
 'allegedli',
 'allegi',
 'allegory',
 'allegra',
 'allen',
 'allerg',
 'allergy',
 'alley',
 'alli',
 'allianc',
 'alliance',
 'allies',
 'alligator',
 'allow',
 'allowed',
 'allur',
 'ally',
 'alma',
 'almightyfantasy',
 'almási',
 'alon',
 'alongsid',
 'aloof',
 'alp',
 'alpha',
 'alps',
 'alpsmountains',
 'alqaeda',
 'alreadi',
 'alt',
 'altar',
 'alter',
 'alterego',
 'altern',
 'alternatedimension',
 'alternatehistory',
 'alternatereality',
 'alternatetimeline',
 'alternateuniverseaction',
 'alternative',
 'alternativerealitycomedy',
 'alternativeuniverse',
 'alternativeworld',
 'alvin',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amateur',
 'amateurdetective',
 'amaz',
 'amazing',
 'amazon',
 'amazonrainforest',
 'amazonriver',
 'ambassador',
 'amber',
 'ambiguity',
 'ambiguoushorror',
 'ambit',
 'ambiti',
 'ambition',
 'ambitions',
 'ambul',
 'ambulance',
 'ambush',
 'amelia',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americancountrysidehorror',
 'americandream',
 'americanfootball',
 'americanfootballcoach',
 'americangiallothriller',
 'americanhistorydrama',
 'americans',
 'americanspycomedy',
 'americanwayoflife',
 'americanwest',
 'americanwilderness',
 'ami',
 'amiabl',
 'amid',
 'amidst',
 'amish',
 'amiti',
 'amnesia',
 'amnesiac',
 'amok',
 'amor',
 'amputation',
 'amsterdam',
 'amulet',
 'amus',
 'amused',
 'amusedaction',
 'amusedcomedy',
 'amusementpark',
 'amy',
 'ana',
 'anaconda',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'anarchiccomedycomedi',
 'anarchist',
 'anastasia',
 'ancestor',
 'ancestry',
 'anchor',
 'anchorman',
 'ancient',
 'ancientcivilization',
 'ancientegypt',
 'ancientevil',
 'ancientgreece',
 'ancientrome',
 'ancientwarfare',
 'ancientworld',
 'anderson',
 'anderton',
 'andesmountains',
 'andi',
 'andrew',
 'androgyny',
 'android',
 'andy',
 'angel',
 'angela',
 'angeles',
 'angelov',
 'angels',
 'anger',
 'angerissuescomedi',
 'angermanagement',
 'angri',
 'angry',
 'angrymob',
 'angst',
 'ani',
 'anim',
 'animal',
 'animalattack',
 'animalcruelty',
 'animalhorror',
 'animalhorroraction',
 'animalkilling',
 'animallead',
 'animalmask',
 'animalrights',
 'animals',
 'animalsidekick',
 'animalsidekickadventure',
 'animated',
 'animatedscene',
 'animation',
 'anime',
 'animeaction',
 'animeadventure',
 'animeanimation',
 'animefantasy',
 'anita',
 'ann',
 'anna',
 'annabel',
 'annabelle',
 'anne',
 'anni',
 'annie',
 'annihil',
 'annihilation',
 'annika',
 'anniversari',
 'announc',
 'annoy',
 'annual',
 'anomaly',
 'anonym',
 'anonymity',
 'anonymousletter',
 'anorexia',
 'anoth',
 'anotherdimension',
 'anselmi',
 'answer',
 'answeringmachine',
 'answers',
 'ant',
 'antagonistic',
 'antagonistichorror',
 'antarctica',
 'anthology',
 'anthoni',
 'anthropologist',
 'anthropology',
 'anthropomorphicanimalsciencefiction',
 'anthropomorphism',
 'anti',
 'antic',
 'anticip',
 'antics',
 'antidote',
 'antihero',
 'antiqu',
 'antique',
 'antisocialpersonalitydisorder',
 'antiwar',
 'antiwardrama',
 'antoin',
 'anton',
 'antonio',
 'anubis',
 'anxieti',
 'anxiety',
 'anxiou',
 'anxious',
 'anybodi',
 'anymore',
 'anyon',
 'anyth',
 'anywher',
 'aokigahara',
 'apart',
 'apartheid',
 'apartment',
 'apartmentbuilding',
 'ape',
 'apeaction',
 'apes',
 'aphrodisiac',
 'apocalypse',
 'apocalypt',
 'apocalypticfuture',
 'apokoliptian',
 'apollo',
 'apostle',
 'app',
 'appalachia',
 'appalachian',
 'appar',
 'apparit',
 'apparition',
 'appeal',
 'appear',
 'appearance',
 'appears',
 'appetit',
 'appl',
 'apple',
 'appletree',
 'appli',
 'appoint',
 'appreci',
 'appreciative',
 'apprehend',
 'apprentic',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'aquat',
 'ar',
 'arab',
 'arabia',
 'arabian',
 'arabiannights',
 'aragorn',
 'aram',
 'arbitrarylaw',
 'arcade',
 'arcadegame',
 'arch',
 'archaeolog',
 'archaeologicalexpedition',
 'archaeologist',
 'archdiocese',
 'archenemi',
 'archeology',
 'archer',
 'archery',
 'archibald',
 'architect',
 'architecture',
 'archiv',
 'arctic',
 'arcticpolarcircleregion',
 'arduou',
 'area',
 'area51',
 'aren',
 'arena',
 'argentina',
 'argument',
 'ariel',
 'aris',
 'arises',
 'aristocracy',
 'aristocrat',
 'arizona',
 'ark',
 'arkansa',
 'arkansas',
 'arkin',
 'arkofthecovenant',
 'arm',
 'armada',
 'armageddon',
 'armand',
 'armedrobbery',
 'armi',
 'armor',
 'armoredcar',
 'arms',
 'armsdeal',
 'armsdealer',
 'armssmuggling',
 'armstrong',
 'army',
 'armybase',
 'armycaptain',
 'armygeneral',
 'armyveteran',
 'arnie',
 'arnold',
 'aroundtheworld',
 'arrang',
 'arrangedmarriage',
 'array',
 'arren',
 'arrest',
 'arrested',
 'arriv',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrog',
 'arrogance',
 'arrogant',
 'arrow',
 'arson',
 'art',
 'artagnan',
 'artcollector',
 'artdealer',
 'artemi',
 'artgallery',
 'arthistory',
 'arthouse',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artificialinsemination',
 'artificialintelligence',
 'artist',
 'artists',
 'artmuseum',
 'arts',
 'artschool',
 'arttheft',
 'artthief',
 'artwork',
 'asami',
 'ascend',
 'ascens',
 'asgard',
 'asger',
 'ash',
 'ashitaka',
 'ashley',
 'ashore',
 'ashtray',
 'asia',
 'asian',
 'asianamerican',
 'asianamericancomedy',
 'asianorigins',
 'asid',
 'ask',
 'asleep',
 'aspect',
 'aspen',
 'asperger',
 'aspir',
 'aspiration',
 'aspiringactor',
 'aspiringsinger',
 'aspiringwriter',
 'ass',
 'assail',
 'assassin',
 'assassination',
 'assassinationattempt',
 'assassinationplot',
 'assassinationteam',
 'assassins',
 'assault',
 'assaultrifle',
 'assembl',
 'assert',
 'assess',
 'asset',
 'assign',
 'assignment',
 'assimil',
 'assist',
 'assistant',
 'associ',
 'associate',
 'assort',
 'assum',
 'assumedidentity',
 'assur',
 'asterix',
 'asteroid',
 'astonish',
 'astound',
 'astro',
 'astronaut',
 'astronautdrama',
 'astronom',
 'astronomer',
 'astrophysicist',
 'asuka',
 'asylum',
 'atenton',
 'atheist',
 'athena',
 'athlet',
 'atlant',
 'atlanta',
 'atlantean',
 ...]

## calculate the Similarity

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
similarity = cosine_similarity(vector)

In [41]:
similaritydf=pd.DataFrame(similarity,index=df['title'],columns=df['title'])
similaritydf

title,Inception,Interstellar,The Dark Knight,Avatar,The Avengers,Deadpool,Avengers: Infinity War,Fight Club,Guardians of the Galaxy,Pulp Fiction,...,Undisputed II: Last Man Standing,The Fan,Demon Slayer: Kimetsu no Yaiba -To the Swordsmith Village-,Prey,Sunrise: A Song of Two Humans,Summer of 85,After Yang,Like a Cat on a Highway 2,Free Birds,Cassandra's Dream
title,,,,,,,,,,,,,,,,,,,,,
Inception,1.000000,0.039918,0.003352,0.011424,0.020848,0.013963,0.006928,0.000000,0.068055,0.032350,...,0.014799,0.033630,0.019019,0.000000,0.005075,0.050640,0.037264,0.009944,0.000000,0.000000
Interstellar,0.039918,1.000000,0.000000,0.066865,0.008418,0.000000,0.037810,0.015236,0.074993,0.014449,...,0.008156,0.000000,0.008182,0.000000,0.049083,0.009728,0.085698,0.000000,0.024957,0.004191
The Dark Knight,0.003352,0.000000,1.000000,0.000000,0.042632,0.044079,0.036292,0.000000,0.019937,0.026335,...,0.024165,0.011091,0.022119,0.000000,0.002228,0.000000,0.003692,0.021438,0.000000,0.023380
Avatar,0.011424,0.066865,0.000000,1.000000,0.000000,0.007776,0.034190,0.000000,0.021952,0.000000,...,0.014395,0.006633,0.016102,0.000000,0.000000,0.010229,0.045248,0.000000,0.000000,0.009452
The Avengers,0.020848,0.008418,0.042632,0.000000,1.000000,0.041366,0.113161,0.000000,0.159830,0.009724,...,0.000000,0.016326,0.000000,0.000000,0.000000,0.008999,0.000000,0.000000,0.016265,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Summer of 85,0.050640,0.009728,0.000000,0.010229,0.008999,0.014373,0.006597,0.004500,0.010777,0.023783,...,0.023848,0.000000,0.000000,0.014246,0.000000,1.000000,0.013956,0.000000,0.038620,0.004480
After Yang,0.037264,0.085698,0.003692,0.045248,0.000000,0.015379,0.022008,0.014350,0.010715,0.004308,...,0.016300,0.012080,0.011069,0.000000,0.018599,0.013956,1.000000,0.024709,0.000000,0.005205
Like a Cat on a Highway 2,0.009944,0.000000,0.021438,0.000000,0.000000,0.032340,0.043023,0.000000,0.043294,0.005094,...,0.011731,0.032901,0.013088,0.000000,0.006610,0.000000,0.024709,1.000000,0.000000,0.000000
Free Birds,0.000000,0.024957,0.000000,0.000000,0.016265,0.000000,0.000000,0.011424,0.000000,0.012311,...,0.046921,0.013303,0.007674,0.000000,0.000000,0.038620,0.000000,0.000000,1.000000,0.000000
Cassandra's Dream,0.000000,0.004191,0.023380,0.009452,0.000000,0.011860,0.000000,0.000000,0.000000,0.010517,...,0.019299,0.016169,0.030551,0.023310,0.034294,0.004480,0.005205,0.000000,0.000000,1.000000

In [42]:
similaritydf['Inception'].sort_values(ascending=False)[1:6]

title
Upgrade                            0.099932
The Matrix                         0.096510
The Matrix Revolutions             0.094709
Charlie's Angels: Full Throttle    0.093025
The Spy Who Dumped Me              0.088126
Name: Inception, dtype: float64

In [43]:
similaritydf['Avatar'].sort_values(ascending=False)[1:6]

title
Battle: Los Angeles    0.140678
Aliens                 0.138970
Apollo 18              0.138863
Predators              0.135235
Meet Dave              0.133644
Name: Avatar, dtype: float64

In [47]:
import numpy as np

In [48]:
df[df['title']=='Avatar'].index[0]

np.int64(3)

In [49]:
def recommen(movie):
    idx = df[df['title']==movie].index[0]
    movie_list=np.argsort(similaritydf.iloc[idx])[::-1][1:6]
    return df.iloc[movie_list].title.tolist()

In [50]:
recommen('Avatar')

['Battle: Los Angeles', 'Aliens', 'Apollo 18', 'Predators', 'Meet Dave']

In [51]:
recommen('Predator')

['Predator 2', 'Predators', 'The Losers', 'Rim of the World', 'The Predator']

In [52]:
df['poster_path']

0       /oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1       /gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2       /qJ2tW6WMUDux911r6m7haRef0WH.jpg
3       /kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4        /RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
                      ...
4995    /rkJKDC5gYrPXQx9IqNaUhSb3beC.jpg
4996    /qjEuDeKOhA7JqaaqhLSfoS9titb.jpg
4997    /2dQ7CILvIXl1Yw0ZXtq5XYqjeqy.jpg
4998    /gnSU2wUBq2gTkBEkxY8C1d1fXAQ.jpg
4999    /hydGWxW9VvRXMwpwFacl7XVtoeR.jpg
Name: poster_path, Length: 5000, dtype: object

In [53]:
print('https://image.tmdb.org/t/p/.')

https://image.tmdb.org/t/p/.

In [54]:
baseurl =('https://image.tmdb.org/t/p/w500')
print(baseurl + '/m73KqOLXf9ZvPVCWS5dz5Hv7yQF.jpg')

https://image.tmdb.org/t/p/w500/m73KqOLXf9ZvPVCWS5dz5Hv7yQF.jpg

In [55]:
import pickle

with open(r'C:\Users\putna\Downloads\recomandation sysytem\similarity.pkl','wb') as file:
    similarity = pickle.dump(similarity,file)